version: "3"

services:
  configuracion:
    image: josecl200/isc517finalconfigserver
    networks:
      - final
    volumes:
    - /home/josecl200/configsFinal:/var/centralConf
    ports:
    - 8888:8888
    restart: on-failure
    logging:
      driver: none


  descubrimiento:
    image: josecl200/isc517finalmicrodiscovery
    networks:
      - final
    depends_on:
      - configuracion
    ports:
    - 8761:8761
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
    restart: on-failure
    logging:
      driver: none

  perimetral:
    image: josecl200/isc517finalgatewaybalanceador
    networks:
      - final
    depends_on:
      - configuracion
      - descubrimiento
    ports:
    - 8080:8080
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
    restart: on-failure
    logging:
      driver: none

  usuariomicro1:
    image: josecl200/isc517finalusuariomicro
    networks:
      - final
    depends_on:
      - dbusuario
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbusuario:3306/usuariomicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  usuariomicro2:
    image: josecl200/isc517finalusuariomicro
    networks:
      - final
    depends_on:
      - dbusuario
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbusuario:3306/usuariomicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2
  usuariomicro3:
    image: josecl200/isc517finalusuariomicro
    networks:
      - final
    depends_on:
      - dbusuario
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbusuario:3306/usuariomicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  comprasmicro1:
    image: josecl200/isc517finalcompramicro
    networks:
      - final
    depends_on:
      - dbcompra
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbcompra:3306/compramicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2
  comprasmicro2:
    image: josecl200/isc517finalcompramicro
    networks:
      - final
    depends_on:
      - dbcompra
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbcompra:3306/compramicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2
  comprasmicro3:
    image: josecl200/isc517finalcompramicro
    networks:
      - final
    depends_on:
      - dbcompra
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbcompra:3306/compramicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  notificacionesmicro1:
    image: josecl200/isc517finalnotificacionesmicro
    networks:
      - final
    depends_on:
      - dbcompra
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbnotif:3306/notificacionesmicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  notificacionesmicro2:
    image: josecl200/isc517finalnotificacionesmicro
    networks:
      - final
    depends_on:
      - dbcompra
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbnotif:3306/notificacionesmicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2

  notificacionesmicro3:
    image: josecl200/isc517finalnotificacionesmicro
    networks:
      - final
    depends_on:
      - dbcompra
      - configuracion
      - descubrimiento
      - perimetral
    expose:
      - 200-65000
    environment:
      - spring.cloud.config.uri=http://configuracion:8888
      - eureka.client.serviceUrl.defaultZone=http://descubrimiento:8761/eureka
      - spring.datasource.url=jdbc:mysql://dbnotif:3306/notificacionesmicro
      - SENDGRID_API_KEY="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"
    restart: on-failure:2


  dbusuario:
    image: library/mysql:latest
    networks:
      - final
    ports:
      - "33006:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=usuariomicro
    volumes:   #volumen de datos utilizado.
      - ~/dato_mysql_final:/var/lib/mysql
  dbcompra:
    image: library/mysql:latest
    networks:
      - final
    ports:
      - "33008:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=compramicro
    volumes:   #volumen de datos utilizado.
      - ~/dato_mysql_compra:/var/lib/mysql

  dbnotif:
    image: library/mysql:latest
    networks:
      - final
    ports:
      - "33009:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notificacionesmicro
    volumes:   #volumen de datos utilizado.
      - ~/dato_mysql_notif:/var/lib/mysql
networks:
  final:
